---
apiVersion: v1
kind: pods
namespace: default
metadata:
  labels:
    app: springboot-app-1
  name: springboot-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app-1
  template:
    metadata:
      labels:
        app: springboot-app-1
    spec:
      containers:
      - name: private-reg-container
        image: ramakrishna8253/week:v5
      imagePullSecrets:
      - name: registry-credential-rama
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app-1
    k8s-app: springboot-app-1
  name: springboot-app-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app-1
