apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJyYW1ha3Jpc2huYTgyNTQiLCJwYXNzd29yZCI6IkRpZ2l0YWxXMHJsZCIsImVtYWlsIjoicmFtYWtyaXNobmE4MjU0QGdtYWlsLmNvbSIsImF1dGgiOiJjbUZ0WVd0eWFYTm9ibUU0TWpVME9rUnBaMmwwWVd4WE1ISnNaQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2023-09-06T11:40:33Z"
  name: registry-credential-rama
  namespace: default
  resourceVersion: "42649569"
  uid: f6138731-5051-43a1-b8bf-b4b2a61b1445
type: kubernetes.io/dockerconfigjson
